# Generated by Django 5.0.7 on 2024-08-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusnesApp', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsOpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunities', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'HeroSection', 'verbose_name_plural': 'HeroSections'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='opportunities',
        ),
    ]
