# Generated by Django 5.0.7 on 2024-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusnesApp', '0006_skills_alter_whyus_options_alter_whyusqa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillsusage',
            options={'verbose_name': 'SkillsUsage', 'verbose_name_plural': 'SkillsUsage'},
        ),
    ]
