# Generated by Django 5.0.7 on 2024-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusnesApp', '0008_calltoaction_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/portfolio')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='img',
            field=models.ImageField(upload_to='media/call to action'),
        ),
    ]
