# Generated by Django 5.0.7 on 2024-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusnesApp', '0010_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubScribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('list_item1', models.CharField(max_length=255)),
                ('list_item2', models.CharField(max_length=255)),
                ('list_item3', models.CharField(max_length=255)),
                ('list_item4', models.CharField(max_length=255)),
                ('list_item5', models.CharField(max_length=255)),
            ],
        ),
    ]
