# Generated by Django 3.2.12 on 2024-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusnesApp', '0015_beginpagecontent_developmentapproach_illustrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.IntegerField()),
                ('notifications', models.IntegerField()),
            ],
            options={
                'verbose_name': 'DashActivity',
                'verbose_name_plural': 'DashActivities',
            },
        ),
        migrations.DeleteModel(
            name='BeginPageContent',
        ),
        migrations.DeleteModel(
            name='DevelopmentApproach',
        ),
        migrations.DeleteModel(
            name='Illustrations',
        ),
        migrations.DeleteModel(
            name='ProjectCard',
        ),
    ]
